version: "3"
services: 
    mediapipe-tf:
        image: nvcr.io/nvidia/dli/dli-nano-ai:v2.0.1-r32.5.0
        container_name: mediapipe-tf
        runtime: nvidia
        networks: 
            - host
        environment: 
            - DISPLAY=$DISPLAY
        volumes: 
            - /tmp/.X11-unix/:/tmp/.X11-unix
            - /tmp/argus_socket:/tmp/argus_socket
        devices: 
            - device /dev/video0
        